### ISSUE TITLE
Screenshot is black

### ISSUE THREAD

**Issue by lindgrenkamali** [ra1nty/DXcam#7] opened 2022-05-20 00:45 UTC
For some reason doesn't this code work.

`camera = dxcam.create()
frame = camera.grab()

Image.fromarray(frame).show()`

It returns a black picture. Have tried `device_idx=0, output_idx=0`, without success, since I use two screens.

**Comment by ra1nty** [comment] 2022-05-20 01:20
Hi,

please supply your Python version, Windows version, the info of dxdiag, and the output of ```dxcam.device_info()``` and ```dxcam.output_info()```

To run dxdiag:
1. win+r; 
2. dxdiag

**Comment by ra1nty** [comment] 2022-05-24 19:17
Hi, I haven't got a chance to test on Win 11. I suspect this might due to some API change in Win 11. I am traveling right now and will attend to this after I'm back.

**Comment by ra1nty** [comment] 2022-05-24 20:21
Might be related: https://github.com/obsproject/obs-studio/issues/5434

**Comment by Rajjco** [comment] 2022-05-25 04:28
Same issue screenshot and Screen Capture  is black for me on Windows 11.

**Comment by ra1nty** [comment] 2022-05-25 05:46
> Same issue screenshot and Screen Capture is black for me on Windows 11. Tried on two PC's one running on integrated intel gpu and other running on dedicated nvidia gpu.

Thanks for the report. Looks like win11 might be an issue. Just curious, was your screen in Portrait mode?

**Comment by ra1nty** [comment] 2022-05-25 06:06
The new win 11 build released 5 days ago might fixed the issue: Windows 11 Build 22000.706 
> We fixed an issue that affects the Desktop Duplication API, which affects display orientation and causes a black image to appear on the screen.

It will be great if someone could test it out.
https://blogs.windows.com/windows-insider/2022/05/19/releasing-windows-11-build-22000-706-to-the-release-preview-channel/

**Comment by Rajjco** [comment] 2022-05-26 13:12
> > Same issue screenshot and Screen Capture is black for me on Windows 11. Tried on two PC's one running on integrated intel gpu and other running on dedicated nvidia gpu.
> 
> Thanks for the report. Looks like win11 might be an issue. Just curious, was your screen in Portrait mode?

Was running in landscape mode normally.

**Comment by oliverbrace** [comment] 2022-06-06 13:17
Hi

I'm running windows 10 with Python version Python 3.10.4 and I'm also getting a black screen.

dxcam.output_info()
Device[0] Output[0]: Res:(3840, 2160) Rot:0 Primary:True

dxcam.device_info()
Device[0]:<Device Name:AMD Radeon RX 5700 XT Dedicated VRAM:8151Mb VendorId:4098>

**Comment by Soikie** [comment] 2022-06-07 14:54
> 

you can try this

```
d =  dxcam.create(device_idx=0, output_idx=0)
img = d.grab()
Image.fromarray(img).show()
```

**Comment by Soikie** [comment] 2022-06-08 09:52
> Sadly still blank. It seems that it is only picking up a single device and output.

you can try this code
```

import dxcam
import numpy as np
from PIL import Image

    
cam = dxcam.create(device_idx=0, output_idx=0)


while True :

    img = cam.grab(region=(0,0,1920,1080))
    if img is not None :
        if np.mean(img)!= 0:
            break

Image.fromarray(img).show()






```

**Comment by oliverbrace** [comment] 2022-06-08 11:53
This just gets stuck in the loop. It could be an issue on my end so I will investigate.

**Comment by oliverbrace** [comment] 2022-06-08 12:21
Not sure it is helpful info but I was able to get it working with d3dshot

```  
d = d3dshot.create()

d.capture()
time.sleep(1)  # Capture is non-blocking so we wait explicitely
d.stop()

img = d.get_latest_frame()
img.show()
```

**Comment by ra1nty** [comment] 2022-06-10 20:20
> 

Hi Oliver,

Thanks for the report. Could you supply the full code snippet to reproduce? I primarily tested on Nvidia GPUs & Python 3.7-10 so I am not sure if the issue could be due to Radeon. But in theory, it should work no matter the vendor.

**Comment by hopepanwei** [comment] 2022-07-16 14:29
I have the same problem
The screenshot is only 1KB ，It's a pure black area，

Device[0]:<Device Name:NVIDIA GeForce RTX 3080 Dedicated VRAM:12116Mb VendorId:4318>
Device[0] Output[0]: Res:(2048, 1152) Rot:0 Primary:True

my environment: 
Python 3.9.13
Nvidia 3080
Windows 11  22000.778

```
camera = dxcam.create(output_color="BGR") 
while True:
  left, top = (2560 - 640) // 2, (1440 - 640) // 2
  right, bottom = left + 640, top + 640
  img0 = camera.grab(region=(left, top, right, bottom)) 
  # Image.fromarray(img0).save(str(time.time()) + ".png")
  try:
    img = img0.transpose((2, 0, 1))[::-1]
  except Exception as e:
    # I need to catch this exception, otherwise it will be thrown: <'NoneType' object has no attribute 'transpose'>
  continue
  img = np.ascontiguousarray(img)
  img = torch.from_numpy(img).to(device)
```

If I need any more information, I can continue to add. I hope to get your help

**Comment by Spexivus** [comment] 2022-07-16 20:56
Trying adding time.sleep(0.1) after initializing the camera

**Comment by ra1nty** [comment] 2022-09-04 21:18
Should be fixed in the release: https://pypi.org/project/dxcam/0.0.5/

**Closed by ra1nty** 2022-09-04 21:18 UTC
Labels: bug, Windows 11

**Comment by ltto** [comment] 2023-05-18 03:45
This problem only exists
C:\Users\Administrator\.conda\envs\p38\python.exe D:/pythonProject_xyq/main_.py 
Device[0]:<Device Name:NVIDIA GeForce RTX 3090 Dedicated VRAM:24340Mb VendorId:4318>

Device[0] Output[0]: Res:(1920, 1080) Rot:0 Primary:True

**Comment by ltto** [comment] 2023-05-18 03:45
![image](https://github.com/ra1nty/DXcam/assets/24884691/b8b2c953-46fe-4f49-81e9-df5378529325)
![image](https://github.com/ra1nty/DXcam/assets/24884691/04aff242-234f-491c-b895-c13973dfc7ae)

**Comment by ParticleG** [comment] 2023-06-02 11:12
> This problem only exists C:\Users\Administrator.conda\envs\p38\python.exe D:/pythonProject_xyq/main_.py Device[0]:<Device Name:NVIDIA GeForce RTX 3090 Dedicated VRAM:24340Mb VendorId:4318>
> 
> Device[0] Output[0]: Res:(1920, 1080) Rot:0 Primary:True

If you're using Windows 11, try set `output_color="RGBA"`:
```python
camera = dxcam.create(output_color="RGBA")
```
It seems that Microsoft update their DX API with alpha channel, if you didn't specify `RGBA` or `BGRA`, the stream data would be corrupted

**Comment by szpnygo** [comment] 2023-06-11 14:33
still black

**Comment by ParticleG** [comment] 2023-06-12 00:58
> still black

Try adding longer sleep between `create` and `start`

**Comment by Anonymous-Dragon** [comment] 2023-07-27 22:15
I have this same issue.

Device[0]:<Device Name:AMD Radeon(TM) Graphics Dedicated VRAM:2021Mb VendorId:4098>
Device[1]:<Device Name:AMD Radeon RX 6800S Dedicated VRAM:8146Mb VendorId:4098>

monitor_lol = 0
self.sct = dxcam.create(device_idx=0, output_idx=monitor_lol,output_color="BGR")
cv2.imshow("Image", self.sct.get_latest_frame())
cv2.waitKey(10)
<img width="149" alt="image" src="https://github.com/ra1nty/DXcam/assets/113312393/e9ba1dca-264c-4f90-8a37-3a5e286fe486">

**Comment by CDLLBOSS** [comment] 2024-03-11 23:32
> I have this same issue.
> 
> Device[0]:<Device Name:AMD Radeon(TM) Graphics Dedicated VRAM:2021Mb VendorId:4098> Device[1]:<Device Name:AMD Radeon RX 6800S Dedicated VRAM:8146Mb VendorId:4098>
> 
> monitor_lol = 0 self.sct = dxcam.create(device_idx=0, output_idx=monitor_lol,output_color="BGR") **#I've also tried BGRA** self.sct.start(target_fps=self.ffps, video_mode=False, region=self.skrean)
> 
> cv2.imshow("Image", self.sct.get_latest_frame()) cv2.waitKey(10) <img alt="image" width="149" src="https://private-user-images.githubusercontent.com/113312393/256676168-e9ba1dca-264c-4f90-8a37-3a5e286fe486.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMDAyNTAsIm5iZiI6MTcxMDE5OTk1MCwicGF0aCI6Ii8xMTMzMTIzOTMvMjU2Njc2MTY4LWU5YmExZGNhLTI2NGMtNGY5MC04YTM3LTNhNWUyODZmZTQ4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQyMzMyMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNGVmNmM5NTI3ODVhYmQzMWJhOTYyMTU5NGVjOTdlMmNhZTI1ZDA1M2EzMTgyMmU0OGY1ODZlMjhjZDQxNDY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j_t58armdVUz54gex9DLJ34oHrUSrMmVQFq2dBbUBzM">
> 
> Windows 11 Pro 64bit

Lmao just set scaling to 100%, thank me later.

**Comment by Janguar02** [comment] 2024-04-18 09:15
> > I have this same issue.
> > Device[0]:<Device Name:AMD Radeon(TM) Graphics Dedicated VRAM:2021Mb VendorId:4098> Device[1]:<Device Name:AMD Radeon RX 6800S Dedicated VRAM:8146Mb VendorId:4098>
> > monitor_lol = 0 self.sct = dxcam.create(device_idx=0, output_idx=monitor_lol,output_color="BGR") **#I've also tried BGRA** self.sct.start(target_fps=self.ffps, video_mode=False, region=self.skrean)
> > cv2.imshow("Image", self.sct.get_latest_frame()) cv2.waitKey(10) <img alt="image" width="149" src="https://private-user-images.githubusercontent.com/113312393/256676168-e9ba1dca-264c-4f90-8a37-3a5e286fe486.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMDAyNTAsIm5iZiI6MTcxMDE5OTk1MCwicGF0aCI6Ii8xMTMzMTIzOTMvMjU2Njc2MTY4LWU5YmExZGNhLTI2NGMtNGY5MC04YTM3LTNhNWUyODZmZTQ4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQyMzMyMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNGVmNmM5NTI3ODVhYmQzMWJhOTYyMTU5NGVjOTdlMmNhZTI1ZDA1M2EzMTgyMmU0OGY1ODZlMjhjZDQxNDY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j_t58armdVUz54gex9DLJ34oHrUSrMmVQFq2dBbUBzM">
> > Windows 11 Pro 64bit
> 
> Lmao just set scaling to 100%, thank me later.

Yep, scaling fixed it

**Comment by Anonymous-Dragon** [comment] 2024-07-08 22:33
What happened with "Automatic handling of scaled / stretched resolution."?
